[versions]
kotlin = "1.9.21"
okhttp = "4.12.0"
slf4j = "2.0.9"

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

maven-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.3" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.7.3" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.0" }

# HTTP Client
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okhttp" }
okhttp-mockws = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

# Mockk
mockk = { module = "io.mockk:mockk", version = "1.13.8" }

# SLF4J
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[bundles]
kotlin = [
    "kotlin-stdlib",
    "kotlin-coroutines-core",
]

kotlin-serialization = [
    "kotlin-serialization-json",
]

slf4j = [
    "slf4j-api",
]

okhttp = [
    "okhttp",
    "okhttp-sse",
]

test-slf4j = [
    "slf4j-simple",
]

test-okhttp = [
    "okhttp-mockws",
    "mockk",
]

test-kotlin = [
    "kotlin-test",
    "kotlin-coroutines-test",
]